### ISSUE TITLE
copy packet in control path to avoid pool starvation

### ISSUE THREAD

**Issue by christophefontaine** [DPDK/grout#111]
Just a note that holding on this packet in control path means that the data path packet pool may end up in a starvation situation. Imagine many packets being queued, with unresolved nh, and no packet left in the packet pool to receive a arp reply.
Grout would probably break from this situation later (as packets are held with a timeout), but still it would be more robust to hold on a packet copy and free the original mbuf.

_Originally posted by @david-marchand in https://github.com/DPDK/grout/pull/109#discussion_r1883750609_

**Comment by david-marchand** [comment]
Duplicate of issue 110 ?

**Comment by christophefontaine** [comment]
indeed, closing.
